title: "Jinhyeong Jeon"
description: "Research notes & projects (OR / Optimization / RL / GNN)"
theme: minima

# Project Pages용 (중요)
url: "https://ruteer9866.github.io"
baseurl: "/ruteer9866.github.io"

# 상단 메뉴
header_pages:
  - projects.md
  - publications.md

# (선택) 블로그 기능은 꺼도/켜도 되는데, 홈페이지 중심이면 없어도 됩니다.